name: advent_of_code_2022
description: My challenges for the Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
dependencies: 
  logging: ^1.1.0
